/*
 * Copyright GroovyFly.com RssEntry.java
 */
package com.groovyfly.controlcentre.structure.sitemanagement;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * @author Chris Hatton
 */
@Entity // @Entity, which means that this is a mapped entity class.
@Table(name = "newsfeedentry") // @Table annotation defines the table name in the database that this entity was being mapped to.
@NamedQueries({
    @NamedQuery(name="NewsFeedEntry.findAll", query="select nfe from NewsFeedEntry nfe")
})
public class NewsFeedEntry implements Serializable {
	
    private static final long serialVersionUID = 8315858877944725668L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // @GeneratedValue annotation tells Hibernate how the id value was generated. this strategy means that the id was generated by the backend sql.
    @Column(name = "id") // column that this property is mapped to. this can be omitted if the name of the property is exactly the same
	private int newsFeedEntryId;
	
    @Column(name = "title")
	private String title;
	
    @Column(name = "link")
	private String link;
	
    @Column(name = "content")
	private String content;
	
    @Column(name = "publicationDate")
	private Date publicationDate;
	
    @Column(name = "retired")
	private boolean retired;

	public int getNewsFeedEntryId() {
		return newsFeedEntryId;
	}

	public void setNewsFeedEntryId(int newsFeedEntryId) {
		this.newsFeedEntryId = newsFeedEntryId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getLink() {
		return link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getPublicationDate() {
		return publicationDate;
	}

	public void setPublicationDate(Date publicationDate) {
		this.publicationDate = publicationDate;
	}

	public boolean isRetired() {
		return retired;
	}

	public void setRetired(boolean retired) {
		this.retired = retired;
	}
	
}
